// This file was generated by language_highlight_autogen.py.
// This should be checked in to version control; it'll be used for other users if autogeneration fails.
#include <array>
extern const std::array<const char*, 983> gSlangHighlightDeclarations;
extern const std::array<const char*, 1164> gSlangHighlightKeywords;
